---
title: "wk4_homework"
output: html_document
date: "2025-10-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Read in files

```{r}
library(sf)
library(here)
# world_shapes <- st_read('world_country_shapes.geojson')
world_shapes <- st_read(here('World_Countries/World_Countries_Generalized.shp'))
```

```{r}
library(tidyverse)
gender_inequity_data <- st_read(here('HDR25_Composite_indices_complete_time_series.csv'))
```

Add correct country code to inequality data
```{r}
library(countrycode)

iso_world <- mutate(
  gender_inequity_data,
  ISO = countrycode(
    gender_inequity_data$iso3,
    origin="iso3c",
    destination = "iso2c"
  )
)
```



Which countries are left out of the gender inequality dataset?
```{r}
filter(world_shapes, !ISO %in% gender_inequity_data$iso3)$COUNTRY
```

# Join data

```{r}
joined_data <- left_join(
  world_shapes,
  iso_world,
  by = join_by(ISO == ISO)
)
```


# Create new column

```{r}
needed_columns = c("ISO", "COUNTRY", "gii_2010", "gii_2019", "geometry")
final_data <- mutate(
  joined_data[,needed_columns],
  gii_2010 = as.numeric(gii_2010),
  gii_2019 = as.numeric(gii_2019),
  difference_in_inequality=gii_2019-gii_2010
)
```

# Plot data

```{r}
library(tmap)

tmap_mode("view")
tm_shape(final_data) +
  tm_basemap(server = "OpenStreetMap") +
  tm_compass(type = "arrow", position = c("left", "bottom")) +
  tm_scalebar(position = c("left", "bottom")) +
  tm_title("Difference in Gender Inequality 2010-2019") +
  tm_polygons(fill="difference_in_inequality",
              fill_alpha=0.8,
              fill.legend = tm_legend(title = "Difference in Inequality", 
                                      size = 0.8))
```

__Alright now lets make a different map shall we!__

What happens if we try to subset the data so that it just shows Papua New Guinea, Australia, East Timor, Malaysia, New Zeland, Brunei, and Solomon Islands

```{r}
print('subset data')

#view(final_data)

countries_list <- c('Australia', 'New Zealand', 'Papua New Guinea', 'Solomon Islands', 'Timor-Leste', 'Indonesia', 'Malaysia', 'Brunei Darussalam') 
new_final_data <- filter(final_data, COUNTRY %in% countries_list)
  
view(new_final_data)
```

```{r}
new_final_data$gii_change_cat <- cut(
  new_final_data$difference_in_inequality,
  breaks = 3,
  labels = c("Low change", "Moderate change", "High change")
)

view(new_final_data)
```

```{r}
library(tmap)

tmap3 <- tm_shape(new_final_data) +
  tm_polygons(
    fill = "gii_change_cat",
    fill.scale = tm_scale(values = c("#3c0008", "#cc7070", "#ff69b4")),
    fill_alpha = 0.8,
    fill.legend = tm_legend(title = "[2010–2019] GII Change")
  ) +
  tm_title("Oceania/SE Asia: GII Change (3 Categories)") +
  tm_credits("Source: UN Human Development Reports", position = c("left", "bottom")) +
  tm_scalebar(position = c("left", "bottom")) +
  tm_layout(legend.col = 1)

tmap3

```

